"""The test suite must not launch a process without the window helper.

Running the suite made the machine unusable: a console application launched from
a test runner inherits a console, and on Windows that opens a window over
whatever the operator was using. The suite launches `git` several times per
fixture, one real MCP server per client, and `pip` plus a fresh interpreter per
packaging gate, so a full run covers the screen with flashing windows.

The fix is a helper, and a helper nobody is required to use is a convention. So
this test makes the requirement structural. It walks the AST of every module
under `tests/` and fails if one calls `subprocess.run`, `subprocess.Popen`, or
any of their siblings directly. The only way to launch a process is
`subproc.run` or `subproc.popen`, which is where the Windows keywords live.

**Why this is a ratchet and not a flat ban.** The census found 131 direct
launches across 40 modules, and this worktree owns six of them. The rest belong
to other owners, so a flat ban would fail on files nobody here may edit, and a
check that fails for reasons outside its owner's control gets deleted rather than
fixed. So the known remainder is pinned by exact count per file, and the failure
modes are the two that matter: a file not in the table at all, or a file with
more launches than the table allows. Both are new code reaching past the helper.
A file *dropping* below its allowance passes, so an owner converting their call
sites never sees this test fight them; the allowance is lowered when they do.

When the table empties this test is a flat ban, and deleting the table is the
only change needed. That is the intended end state, not a rewrite.

Two other things this deliberately does not do. It does not check *whether* a
call sets the keywords, because the helper is the one place they are written and
`test_the_helper_carries_the_windows_keywords_here` covers that half. And it
does not forbid the name `subprocess` in a test that is *about* subprocess, since
several here write source strings they then execute -- the AST walk reads calls,
not text, so a name in a string is not a call.
"""
from __future__ import annotations

import ast
import subprocess
import sys
from pathlib import Path

import pytest

import subproc

TESTS_DIR = Path(__file__).resolve().parent

#: The entry points that create a process. `check_call` and `call` go through
#: `run` internally and would be equally fatal without the keywords, so the list
#: covers the whole surface rather than the two wrappers that happen to be used.
LAUNCHERS = frozenset({"run", "Popen", "call", "check_call", "check_output"})

#: The wrapper module itself, and this file. Both are where the keywords are
#: written, so both are the one place a direct call is correct.
EXEMPT = frozenset({"subproc.py", "test_subprocess_windows.py"})

#: The known remainder, per file. Generated by
#: `python -c "import test_subprocess_windows as t; ..."` and lowered as owners
#: convert their call sites. A file absent from this table, or above its
#: allowance, is a new offender.
ALLOWANCE: dict[str, int] = {
    "test_acceptance.py": 4,
    "test_acceptance02.py": 1,
    "test_claims.py": 2,
    "test_cli.py": 12,
    "test_cli02.py": 6,
    "test_concurrency.py": 2,
    "test_console.py": 10,
    "test_core_acceptance_boundary.py": 8,
    "test_core_admission.py": 4,
    "test_decision_guards.py": 1,
    "test_features.py": 7,
    "test_fixture_git_isolation.py": 2,
    "test_host_session_doc.py": 1,
    "test_idempotency.py": 3,
    "test_identity.py": 1,
    "test_integration.py": 1,
    "test_integration_guards.py": 1,
    "test_mcp.py": 5,
    "test_mcp_contract_schema.py": 1,
    "test_mcp_supervisor_fixtures.py": 5,
    "test_optional_toolchain.py": 1,
    "test_plan06_mcp_inspect.py": 3,
    "test_plan06_onboarding.py": 8,
    "test_plugin.py": 6,
    "test_plugin_host.py": 2,
    "test_plugin_resources.py": 1,
    "test_policy.py": 2,
    "test_process_recovery_regressions.py": 1,
    "test_procidentity.py": 3,
    "test_procidentity_posix.py": 3,
    "test_procs_guards.py": 1,
    "test_r2_ownership.py": 5,
    "test_recover.py": 2,
    "test_recovery07.py": 1,
    "test_release_docs.py": 3,
}


def _imports_subprocess(node: ast.AST) -> str | None:
    """The local name `subprocess` is bound to in this module, or None.

    A module may do `import subprocess as sp`, and a call written `sp.run(...)`
    is the same defect as `subprocess.run(...)`. Resolving the alias is what
    makes this check survive a rename.
    """
    for child in ast.walk(node):
        if isinstance(child, ast.Import):
            for alias in child.names:
                if alias.name == "subprocess":
                    return alias.asname or alias.name
    return None


def _direct_launches(source: str, filename: str) -> list[tuple[int, str]]:
    """Every direct `subprocess` launch in one module, as `(lineno, text)`."""
    tree = ast.parse(source, filename=filename)
    alias = _imports_subprocess(tree)
    if alias is None:
        return []
    found: list[tuple[int, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not isinstance(func, ast.Attribute) or func.attr not in LAUNCHERS:
            continue
        owner = func.value
        if isinstance(owner, ast.Name) and owner.id == alias:
            found.append((node.lineno, f"{alias}.{func.attr}"))
    return sorted(found)


def _test_modules() -> list[Path]:
    """Every module under `tests/`, which is where the suite's own code lives.

    A directory that is not test code is skipped rather than walked. `rglob`
    would otherwise descend into a scratch tree a test left behind and parse
    whatever it found, so the census could depend on which tests ran first.
    """
    return sorted(
        path
        for path in TESTS_DIR.rglob("*.py")
        if path.name not in EXEMPT
        and not any(
            part == "__pycache__" or part.startswith(".")
            for part in path.relative_to(TESTS_DIR).parts
        )
    )


def _observed() -> dict[str, list[tuple[int, str]]]:
    return {
        path.name: _direct_launches(path.read_text(encoding="utf-8"), str(path))
        for path in _test_modules()
    }


def test_no_test_module_launches_a_new_process_directly() -> None:
    """Every *new* process launch in `tests/` goes through `subproc`.

    The AST walk is what makes this worth having. Reading the text for
    `subprocess.run` cannot tell a call from the string a test asserts on, and
    the string cases are exactly the interesting ones: several tests here and in
    the policy suite write source that they then execute.
    """
    observed = {name: sites for name, sites in _observed().items() if sites}

    unlisted = sorted(
        f"{name}:{lineno} {text}"
        for name, sites in observed.items() if name not in ALLOWANCE
        for lineno, text in sites
    )
    grown = sorted(
        f"{name}:{lineno} {text} ({len(observed[name])} sites, allowed "
        f"{ALLOWANCE[name]})"
        for name, sites in observed.items()
        if name in ALLOWANCE and len(sites) > ALLOWANCE[name]
        for lineno, text in sites
    )

    stale = sorted(
        f"{name}: allowed {allowed}, found {len(observed.get(name, []))}"
        for name, allowed in ALLOWANCE.items()
        if name not in observed
    )

    assert not unlisted, (
        "these launch a process without subproc, so on Windows each one puts a "
        "console window on the operator's screen. Call subproc.run or "
        f"subproc.popen instead:\n" + "\n".join(unlisted)
    )
    assert not grown, (
        "these modules have more direct launches than ALLOWANCE records, so the "
        "remainder grew. Use subproc, or raise the allowance deliberately and "
        "say why:\n" + "\n".join(grown)
    )
    assert not stale, (
        "these files no longer appear in the census, so their allowance should "
        "be deleted:\n" + "\n".join(stale)
    )


def test_the_allowance_covers_every_known_offender() -> None:
    """No file is silently exempt, and the table is not wider than the problem.

    A table entry for a file that has since been converted would otherwise sit
    here forever holding a stale number nobody trusts, which is how a ratchet
    decays into a rubber stamp.
    """
    observed = {name: sites for name, sites in _observed().items() if sites}
    assert set(observed) == set(ALLOWANCE), (
        f"the census and the allowance disagree: only in the census "
        f"{sorted(set(observed) - set(ALLOWANCE))}, only in the allowance "
        f"{sorted(set(ALLOWANCE) - set(observed))}"
    )


def test_the_helper_actually_launches() -> None:
    """The wrappers are wired to `subprocess`, not a reimplementation of it.

    Without this the check above would still pass if `subproc.run` were a stub,
    and the suite would silently stop launching anything.
    """
    done = subproc.run([sys.executable, "-c", "print('launched')"], capture_output=True, text=True)
    assert done.returncode == 0, done.stderr
    assert done.stdout.strip() == "launched"

    proc = subproc.popen([sys.executable, "-c", "pass"])
    assert proc.wait(timeout=60) == 0


@pytest.mark.skipif(sys.platform == "win32", reason="asserts the non-Windows shape")
def test_the_helper_adds_nothing_off_windows() -> None:
    """Off Windows the helper passes no `creationflags` and no `startupinfo`.

    Not a style rule. `subprocess.STARTUPINFO` does not exist on POSIX, so a
    helper that built one unconditionally would raise `AttributeError` on the
    first call on Linux or macOS -- and only on the first call, which is the
    worst way to find out.
    """
    assert subproc.hidden_window() == {}
    assert not hasattr(subprocess, "STARTUPINFO"), (
        "this host is POSIX and still exposes STARTUPINFO; the skip above is "
        "misleading and the assertion below proves nothing"
    )
    done = subproc.run([sys.executable, "-c", "print('posix')"], capture_output=True, text=True)
    assert done.stdout.strip() == "posix"


def test_the_helper_carries_the_windows_keywords_here() -> None:
    """On Windows the helper is what sets both keywords.

    Run on this host, whatever it is, so the suite has a positive assertion for
    the behaviour the whole unit exists for rather than only a negative one.
    """
    if sys.platform != "win32":
        pytest.skip("the keywords are Windows-only; the POSIX shape is asserted above")
    keywords = subproc.hidden_window()
    assert keywords["creationflags"] == subprocess.CREATE_NO_WINDOW
    assert keywords["startupinfo"].dwFlags & subprocess.STARTF_USESHOWWINDOW
