"""Check kinds, their obligations, and the adapters that run and read them."""

from .dispatch import ADAPTERS, Adapter, ScenarioReading, argv_for, interpret, outcome_from_reading
from .lean_adapter import AdapterResult as LeanAdapterResult
from .node_adapter import AdapterResult as NodeAdapterResult
from .obligation import (
    CaseObligation,
    Obligation,
    PropertyObligation,
    TheoremObligation,
    describe as describe_obligation,
    obligation_from_json,
    obligation_to_json,
    obligations_from_scenarios,
)
from .property_adapter import PropertyAdapterResult, TestedScope
from .pytest_adapter import AdapterResult
from .spec import (
    VARIANTS,
    CheckKind,
    CheckSpec,
    DomainBounds,
    FingerprintSpec,
    HypothesisSettings,
    LeanCheck,
    LeanProfile,
    ModuleRef,
    NativeCheckSpec,
    NodeTestCheck,
    PinnedRunner,
    PropertyCheck,
    PytestCheck,
    ReplaySettings,
    ScenarioCheck,
    SubjectRef,
    TlcCheck,
    ToolchainRef,
    evidence_kind,
)
from .tlc_adapter import AdapterResult as TlcAdapterResult

__all__ = [
    "ADAPTERS",
    "VARIANTS",
    "Adapter",
    "AdapterResult",
    "CaseObligation",
    "CheckKind",
    "CheckSpec",
    "DomainBounds",
    "FingerprintSpec",
    "HypothesisSettings",
    "LeanAdapterResult",
    "LeanCheck",
    "LeanProfile",
    "ModuleRef",
    "NativeCheckSpec",
    "NodeAdapterResult",
    "NodeTestCheck",
    "Obligation",
    "PinnedRunner",
    "PropertyAdapterResult",
    "PropertyCheck",
    "PropertyObligation",
    "PytestCheck",
    "ReplaySettings",
    "ScenarioCheck",
    "ScenarioReading",
    "SubjectRef",
    "TestedScope",
    "TheoremObligation",
    "TlcAdapterResult",
    "TlcCheck",
    "ToolchainRef",
    "argv_for",
    "describe_obligation",
    "evidence_kind",
    "for_kind",
    "interpret",
    "obligation_from_json",
    "obligation_to_json",
    "obligations_from_scenarios",
    "outcome_from_reading",
]
